const shirts = [
  {
    id: 1,
    name: 'Áo Cardigan Len',
    price: 450000,
    oldPrice: 600000,
    images: [
      '../img/ao/ao_cardigan_len.png',
      '../img/cardigan2.jpg',
      '../img/cardigan3.jpg',
    ],
    description: `Áo cardigan len phong cách vintage, chất liệu len mềm mại, giữ ấm tốt, phù hợp mùa thu đông.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Nâu', 'Be', 'Xanh Rêu'],
    stock: 20,
    category: 'Áo khoác',
    brand: 'Local Brand ABC',
  },
  {
    id: 2,
    name: 'Áo Hoodie Angel',
    price: 520000,
    oldPrice: 650000,
    images: [
      '../img/ao/ao_hoodie_angelic.png',
      '../img/hoodie2.jpg',
      '../img/hoodie3.jpg',
    ],
    description: `Áo hoodie in hình Angel phong cách streetwear, chất liệu nỉ bông ấm áp, form rộng thoải mái.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Trắng', 'Đen', 'Xám'],
    stock: 30,
    category: 'Áo hoodie',
    brand: 'Local Brand XYZ',
  },
  {
    id: 3,
    name: 'Áo Phao Gile',
    price: 590000,
    oldPrice: 750000,
    images: [
      '../img/ao/ao_phao_gile.png',
      '../img/gile2.jpg',
      '../img/gile3.jpg',
    ],
    description: `Áo phao gile giữ ấm tốt, nhẹ và tiện lợi, dễ phối đồ mùa đông.`,
    sizes: ['M', 'L', 'XL'],
    colors: ['Đen', 'Xanh Navy', 'Xám'],
    stock: 15,
    category: 'Áo khoác',
    brand: 'Local Brand MNO',
  },
  {
    id: 4,
    name: 'Áo Sơ Mi Kẻ Sọc',
    price: 350000,
    oldPrice: 450000,
    images: [
      '../img/ao/ao_so_mi_ke_soc.png',
      '../img/somi2.jpg',
      '../img/somi3.jpg',
    ],
    description: `Áo sơ mi kẻ sọc thời trang, chất liệu cotton thoáng mát, phù hợp đi làm và đi chơi.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Trắng-Đen', 'Xanh-Trắng'],
    stock: 40,
    category: 'Áo sơ mi',
    brand: 'Local Brand DEF',
  },
  {
    id: 5,
    name: 'Áo Sweater Nỉ',
    price: 480000,
    oldPrice: 600000,
    images: [
      '../img/ao/ao_sweater_ni.png',
      '../img/sweaterni2.jpg',
      '../img/sweaterni3.jpg',
    ],
    description: `Áo sweater nỉ dày dặn, phong cách streetwear, dễ phối đồ.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Xám', 'Đen', 'Xanh Dương'],
    stock: 28,
    category: 'Áo sweater',
    brand: 'Local Brand GHI',
  },
  {
    id: 6,
    name: 'Áo Sweater Polo',
    price: 520000,
    oldPrice: 680000,
    images: [
      '../img/ao/ao_sweater_polo.png',
      '../img/sweaterpolo2.jpg',
      '../img/sweaterpolo3.jpg',
    ],
    description: `Áo sweater cổ polo, chất liệu mềm mại, mang lại phong cách lịch sự nhưng vẫn thoải mái.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Be', 'Nâu', 'Xanh Navy'],
    stock: 18,
    category: 'Áo sweater',
    brand: 'Local Brand JKL',
  },
  {
    id: 7,
    name: 'Áo Thun Cộc Tay',
    price: 250000,
    oldPrice: 350000,
    images: [
      '../img/ao/ao_thun_coc_tay_7G.png',
      '../img/thun2.jpg',
      '../img/thun3.jpg',
    ],
    description: `Áo thun cộc tay basic, chất liệu cotton co giãn thoáng mát, phù hợp mọi hoạt động.`,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Trắng', 'Đen', 'Xanh Biển'],
    stock: 50,
    category: 'Áo thun',
    brand: 'Local Brand PQR',
  },
  {
    id: 8,
    name: 'Áo Bomber Nam Local Brand',
    price: 650000,
    oldPrice: 850000,
    images: [
      '../img/ao_bomber_mlb_ny/ao_bomber_mlb_black.png',
      '../img/ao_bomber_mlb_ny/ao_bomber_mlb_blue.png',
      '../img/ao_bomber_mlb_ny/ao_bomber_mlb_grey.png',
      '../img/ao_bomber_mlb_ny/form_ao.png',
      '../img/ao_bomber_mlb_ny/form_ao_1.png',
      '../img/ao_bomber_mlb_ny/form_ao_2.png',
    ],
    description: `Áo bomber phong cách streetwear, chất liệu vải dày dặn, giữ ấm tốt và thiết kế form rộng thoải mái.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Đen', 'Xanh Navy', 'Be'],
    stock: 25,
    category: 'Áo khoác',
    brand: 'Local Brand XYZ',
  },
  {
    id: 9,
    name: 'Áo Manchester United mùa 2006-2007',
    price: 222000,
    oldPrice: 350000,
    images: [
      '../img/ao_mu_2006-2007/ao_mu_2006-07.png',
      '../img/ao_mu_2006-2007/logo_canh_tay_ao_mu_2006-07.jpg',
      '../img/ao_mu_2006-2007/logo_clb_mu_2006-07.jpg',
      '../img/ao_mu_2006-2007/lung_ao_mu_2006-07.jpg',
      '../img/ao_mu_2006-2007/rooney.jpg',
      '../img/ao_mu_2006-2007/size_ao_mu_2006-07.png',
    ],
    description: `Áo đá bóng của đội bóng Manchester United mùa 2006-2007 cực kỳ đẹp và đặc sắc.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Đỏ'],
    stock: 25,
    category: 'Áo đá bóng',
    brand: 'Local Brand XYZ',
  },
];
// Pants
const pants = [
  {
    id: 1,
    name: 'Quần jeans dài Wash-Unisex',
    price: 550000,
    oldPrice: 690000,
    images: [
      '../img/quan/quan_jean_dai_wash_unisex.png',
      '../img/pants1-2.jpg',
      '../img/pants1-3.jpg',
    ],
    description: `Quần jeans wash nhẹ, unisex, chất liệu denim co giãn nhẹ, phù hợp đi chơi và dạo phố.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Xanh nhạt', 'Xanh đậm'],
    stock: 20,
    category: 'Quần jeans',
    brand: 'Local Brand XYZ',
  },
  {
    id: 2,
    name: 'Quần jeans nam rách gối khóa zip',
    price: 600000,
    oldPrice: 750000,
    images: [
      '../img/quan/quan_jean_nam_rach_goi_khoa_zip.png',
      '../img/pants2-2.jpg',
      '../img/pants2-3.jpg',
    ],
    description: `Quần jeans nam form slim, rách gối cá tính, có khóa zip trang trí.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Xanh đậm', 'Đen'],
    stock: 18,
    category: 'Quần jeans',
    brand: 'Local Brand XYZ',
  },
  {
    id: 3,
    name: 'Quần jeans túi hộp ống suông unisex',
    price: 620000,
    oldPrice: 780000,
    images: [
      '../img/quan/quan_jean_tui_hop_ong_suong_unisex.png',
      '../img/pants3-2.jpg',
      '../img/pants3-3.jpg',
    ],
    description: `Quần jeans túi hộp rộng rãi, phong cách đường phố, ống suông unisex.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Xanh nhạt', 'Đen'],
    stock: 22,
    category: 'Quần jeans',
    brand: 'Local Brand XYZ',
  },
  {
    id: 4,
    name: 'Quần ống suông nỉ kẻ sọc',
    price: 450000,
    oldPrice: 580000,
    images: [
      '../img/quan/quan_ong_rong_in_soc_HongKong.png',
      '../img/pants4-2.jpg',
      '../img/pants4-3.jpg',
    ],
    description: `Quần nỉ thể thao ống suông, kẻ sọc hai bên, thoải mái khi vận động.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Đen', 'Xám', 'Xanh Navy'],
    stock: 30,
    category: 'Quần thể thao',
    brand: 'Local Brand XYZ',
  },
  {
    id: 5,
    name: 'Quần ống rộng vải kaki T-Home-Wide-Leg',
    price: 580000,
    oldPrice: 720000,
    images: [
      '../img/quan/quan_ong_rong_Thomes_Wide-leg_pants.png',
      '../img/pants5-2.jpg',
      '../img/pants5-3.jpg',
    ],
    description: `Quần kaki ống rộng form T-Home, vải dày dặn, thích hợp mùa thu đông.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Be', 'Đen', 'Nâu'],
    stock: 25,
    category: 'Quần kaki',
    brand: 'Local Brand XYZ',
  },
  {
    id: 6,
    name: 'Quần short jeans form rộng trên gối',
    price: 400000,
    oldPrice: 520000,
    images: [
      '../img/quan/quan_short_jean_form_rong_tren_goi.png',
      '../img/pants6-2.jpg',
      '../img/pants6-3.jpg',
    ],
    description: `Quần short jeans form rộng, dài trên gối, dễ phối đồ mùa hè.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Xanh nhạt', 'Xanh đậm'],
    stock: 28,
    category: 'Quần short',
    brand: 'Local Brand XYZ',
  },
  {
    id: 7,
    name: 'Quần short nỉ dây thun dài',
    price: 380000,
    oldPrice: 490000,
    images: [
      '../img/quan/quan_short_vai_ni_form_rong.png',
      '../img/pants7-2.jpg',
      '../img/pants7-3.jpg',
    ],
    description: `Quần short nỉ co giãn, có dây thun dài, thoải mái và năng động.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Đen', 'Xám'],
    stock: 32,
    category: 'Quần short',
    brand: 'Local Brand XYZ',
  },
  {
    id: 8,
    name: 'Quần âu ống suông vải trơn',
    price: 650000,
    oldPrice: 800000,
    images: [
      '../img/quan_au_nam_ong_suong/quan_au_1.png',
      '../img/quan_au_nam_ong_suong/quan_au_2.png',
      '../img/quan_au_nam_ong_suong/quan_au_black.png',
      '../img/quan_au_nam_ong_suong/quan_au_gray.png',
      '../img/quan_au_nam_ong_suong/quan_au_milky_white.png',
      '../img/quan_au_nam_ong_suong/size.png',
    ],
    description: `Quần âu ống suông vải trơn, thích hợp mặc đi làm hoặc sự kiện.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Đen', 'Xám', 'Be'],
    stock: 15,
    category: 'Quần âu',
    brand: 'Local Brand XYZ',
  },
];

// Shoes
const shoes = [
  {
    id: 1,
    name: 'Giày Adidas SuperStar',
    price: 1800000,
    oldPrice: 2100000,
    images: [
      '../img/giay/giay_adidas_adiform_superstar.png',
      '../img/shoes1-2.jpg',
      '../img/shoes1-3.jpg',
    ],
    description: `Giày Adidas SuperStar cổ điển với thiết kế mũi vỏ sò đặc trưng.`,
    sizes: ['38', '39', '40', '41', '42', '43'],
    colors: ['Trắng', 'Đen'],
    stock: 20,
    category: 'Giày sneaker',
    brand: 'Adidas',
  },
  {
    id: 2,
    name: 'Giày Chelsea Boot nam da bò',
    price: 2200000,
    oldPrice: 2500000,
    images: [
      '../img/giay/giay_chelsea_boot_nam_da_bo.png',
      '../img/shoes2-2.jpg',
      '../img/shoes2-3.jpg',
    ],
    description: `Chelsea Boot nam da bò thật, phong cách sang trọng.`,
    sizes: ['39', '40', '41', '42', '43', '44'],
    colors: ['Đen', 'Nâu'],
    stock: 12,
    category: 'Giày boot',
    brand: 'Local Brand XYZ',
  },
  {
    id: 3,
    name: 'Giày Converse Chuck-Taylor-Chrismas',
    price: 1500000,
    oldPrice: 1700000,
    images: [
      '../img/giay/giay_converse_Chuck_Taylor_Christmas.png',
      '../img/shoes3-2.jpg',
      '../img/shoes3-3.jpg',
    ],
    description: `Converse Chuck Taylor phiên bản Giáng Sinh, họa tiết đặc biệt.`,
    sizes: ['38', '39', '40', '41', '42', '43'],
    colors: ['Đỏ', 'Trắng'],
    stock: 18,
    category: 'Giày sneaker',
    brand: 'Converse',
  },
  {
    id: 4,
    name: 'Giày Jordan Four Military',
    price: 3500000,
    oldPrice: 3800000,
    images: [
      '../img/giay/giay_jordan_4_Military.png',
      '../img/shoes4-2.jpg',
      '../img/shoes4-3.jpg',
    ],
    description: `Jordan Four Military phong cách thể thao, chất liệu cao cấp.`,
    sizes: ['39', '40', '41', '42', '43', '44'],
    colors: ['Trắng', 'Xám'],
    stock: 10,
    category: 'Giày sneaker',
    brand: 'Nike',
  },
  {
    id: 5,
    name: 'Giày New Balance',
    price: 1900000,
    oldPrice: 2200000,
    images: [
      '../img/giay/giay_new_balance_574.png',
      '../img/shoes5-2.jpg',
      '../img/shoes5-3.jpg',
    ],
    description: `Giày New Balance phong cách retro, êm ái khi di chuyển.`,
    sizes: ['38', '39', '40', '41', '42', '43'],
    colors: ['Xám', 'Xanh'],
    stock: 15,
    category: 'Giày sneaker',
    brand: 'New Balance',
  },
  {
    id: 6,
    name: 'Giày Samba OG 3 sọc',
    price: 1700000,
    oldPrice: 1900000,
    images: [
      '../img/giay/giay_samba_OG_3_soc.png',
      '../img/shoes6-2.jpg',
      '../img/shoes6-3.jpg',
    ],
    description: `Giày Samba OG 3 sọc, kiểu dáng cổ điển, dễ phối đồ.`,
    sizes: ['38', '39', '40', '41', '42', '43'],
    colors: ['Trắng', 'Đen'],
    stock: 22,
    category: 'Giày sneaker',
    brand: 'Adidas',
  },
  {
    id: 7,
    name: 'Giày Sneaker Blazer Mid 77',
    price: 2000000,
    oldPrice: 2300000,
    images: [
      '../img/giay/giay_sneaker_blazer_mid_77_co_cao.png',
      '../img/shoes7-2.jpg',
      '../img/shoes7-3.jpg',
    ],
    description: `Nike Blazer Mid 77 phong cách vintage, form cao.`,
    sizes: ['38', '39', '40', '41', '42', '43'],
    colors: ['Trắng', 'Be'],
    stock: 14,
    category: 'Giày sneaker',
    brand: 'Nike',
  },
  {
    id: 8,
    name: 'Giày Air Jordan',
    price: 3200000,
    oldPrice: 3500000,
    images: [
      '../img/giay_air_jordan_1_Retro_High_OG/giay_air_jordan_1.png',
      '../img/giay_air_jordan_1_Retro_High_OG/giay_air_jordan_2.png',
      '../img/giay_air_jordan_1_Retro_High_OG/giay_air_jordan_mau_nguoi.png',
      '../img/giay_air_jordan_1_Retro_High_OG/giay_air_jordan_mocha.png',
      '../img/giay_air_jordan_1_Retro_High_OG/giay_air_jordan_panda.png',
      '../img/giay_air_jordan_1_Retro_High_OG/giay_air_jordan_red.png',
    ],
    description: `Air Jordan phong cách thể thao, đế êm và bền.`,
    sizes: ['39', '40', '41', '42', '43', '44'],
    colors: ['Đen', 'Trắng', 'Đỏ'],
    stock: 12,
    category: 'Giày sneaker',
    brand: 'Nike',
  },
];
