const shirts = [
  {
    id: 1,
    type: 'shirts',
    name: 'Áo Cardigan Len',
    price: 450000,
    oldPrice: 600000,
    images: [
      '../img/ao/ao_cardigen/ao_cardigan_len.png',
      '../img/ao/ao_cardigen/ao_cardigan_len1.png',
      '../img/ao/ao_cardigen/ao_cardigan_len2.png',
      '../img/ao/ao_cardigen/ao_cardigan_len3.png',
      '../img/ao/ao_cardigen/ao_cardigan_len4.png',
    ],
    description: `Áo cardigan len phong cách vintage, chất liệu len mềm mại, giữ ấm tốt, phù hợp mùa thu đông.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Nâu', 'Be', 'Xám ghi'],
    stock: 20,
    category: 'Áo khoác',
    brand: 'Local Brand ABC',
  },
  {
    id: 2,
    type: 'shirts',
    name: 'Áo Hoodie Angel',
    price: 520000,
    oldPrice: 650000,
    images: [
      '../img/ao/ao_hoddie_angleic/ao_hoodie_angelic.png',
      '../img/ao/ao_hoddie_angleic/ao_hoodie_angelic1.png',
      '../img/ao/ao_hoddie_angleic/ao_hoodie_angelic2.png',
      '../img/ao/ao_hoddie_angleic/ao_hoodie_angelic3.png',
      '../img/ao/ao_hoddie_angleic/ao_hoodie_angelic4.png',
    ],
    description: `Áo hoodie in hình Angel phong cách streetwear, chất liệu nỉ bông ấm áp, form rộng thoải mái.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Đen', 'Xám'],
    stock: 30,
    category: 'Áo hoodie',
    brand: 'Local Brand XYZ',
  },
  {
    id: 3,
    type: 'shirts',
    name: 'Áo Phao Gile',
    price: 590000,
    oldPrice: 750000,
    images: [
      '../img/ao/ao_phao_gile/ao_phao_gile.png',
      '../img/ao/ao_phao_gile/ao_phao_gile1.png',
      '../img/ao/ao_phao_gile/ao_phao_gile2.png',
      '../img/ao/ao_phao_gile/ao_phao_gile3.png',
      '../img/ao/ao_phao_gile/ao_phao_gile4.png',
    ],
    description: `Áo phao gile giữ ấm tốt, nhẹ và tiện lợi, dễ phối đồ mùa đông.`,
    sizes: ['M', 'L', 'XL'],
    colors: ['Đen', 'Nâu'],
    stock: 15,
    category: 'Áo khoác',
    brand: 'Local Brand MNO',
  },
  {
    id: 4,
    type: 'shirts',
    name: 'Áo Sơ Mi Kẻ Sọc',
    price: 350000,
    oldPrice: 450000,
    images: [
      '../img/ao/ao_so_mi_ke_soc/ao_so_mi_ke_soc.png',
      '../img/ao/ao_so_mi_ke_soc/ao_so_mi_ke_soc1.png',
      '../img/ao/ao_so_mi_ke_soc/ao_so_mi_ke_soc2.png',
      '../img/ao/ao_so_mi_ke_soc/ao_so_mi_ke_soc3.png',
      '../img/ao/ao_so_mi_ke_soc/ao_so_mi_ke_soc4.png',
    ],
    description: `Áo sơ mi kẻ sọc thời trang, chất liệu cotton thoáng mát, phù hợp đi làm và đi chơi.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Đen', 'Xanh', 'Nâu'],
    stock: 40,
    category: 'Áo sơ mi',
    brand: 'Local Brand DEF',
  },
  {
    id: 5,
    type: 'shirts',
    name: 'Áo Sweater Nỉ',
    price: 480000,
    oldPrice: 600000,
    images: [
      '../img/ao/ao_sweater_ni/ao_sweater_ni.png',
      '../img/sweaterni2.jpg',
      '../img/sweaterni3.jpg',
    ],
    description: `Áo sweater nỉ dày dặn, phong cách streetwear, dễ phối đồ.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Xám', 'Đen', 'Xanh Dương'],
    stock: 28,
    category: 'Áo sweater',
    brand: 'Local Brand GHI',
  },
  {
    id: 6,
    type: 'shirts',
    name: 'Áo Sweater Polo',
    price: 520000,
    oldPrice: 680000,
    images: [
      '../img/ao/ao_sweater_polo/ao_sweater_polo.jpg',
      '../img/ao/ao_sweater_polo/ao_sweater_polo1.jpg',
      '../img/ao/ao_sweater_polo/ao_sweater_polo2.jpg',
      '../img/ao/ao_sweater_polo/ao_sweater_polo3.jpg',
      '../img/ao/ao_sweater_polo/ao_sweater_polo4.jpg',
    ],
    description: `Áo sweater cổ polo, chất liệu mềm mại, mang lại phong cách lịch sự nhưng vẫn thoải mái.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Đen', 'Xám', 'Xanh Navy'],
    stock: 18,
    category: 'Áo sweater',
    brand: 'Local Brand JKL',
  },
  {
    id: 7,
    type: 'shirts',
    name: 'Áo Thun Cộc Tay',
    price: 250000,
    oldPrice: 350000,
    images: [
      '../img/ao/ao_thun_coc_tay_7G/ao_thun_coc_tay_7G.png',
      '../img/ao/ao_thun_coc_tay_7G/ao_thun_coc_tay_7G1.png',
      '../img/ao/ao_thun_coc_tay_7G/ao_thun_coc_tay_7G2.png',
      '../img/ao/ao_thun_coc_tay_7G/ao_thun_coc_tay_7G3.png',
      '../img/ao/ao_thun_coc_tay_7G/ao_thun_coc_tay_7G4.png',
    ],
    description: `Áo thun cộc tay basic, chất liệu cotton co giãn thoáng mát, phù hợp mọi hoạt động.`,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Trắng', 'Xám', 'Đen', 'Xanh Biển'],
    stock: 50,
    category: 'Áo thun',
    brand: 'Local Brand PQR',
  },
  {
    id: 8,
    type: 'shirts',
    name: 'Áo Bomber Nam Local Brand',
    price: 650000,
    oldPrice: 850000,
    images: [
      '../img/ao/ao_bomber_mlb_ny/ao_bomber_mlb_black.png',
      '../img/ao/ao_bomber_mlb_ny/ao_bomber_mlb_blue.png',
      '../img/ao/ao_bomber_mlb_ny/ao_bomber_mlb_grey.png',
      '../img/ao/ao_bomber_mlb_ny/form_ao.png',
      '../img/ao/ao_bomber_mlb_ny/form_ao_1.png',
      '../img/ao/ao_bomber_mlb_ny/form_ao_2.png',
    ],
    description: `Áo bomber phong cách streetwear, chất liệu vải dày dặn, giữ ấm tốt và thiết kế form rộng thoải mái.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Đen', 'Xanh Navy', 'Be'],
    stock: 25,
    category: 'Áo khoác',
    brand: 'Local Brand XYZ',
  },
  {
    id: 9,
    type: 'shirts',
    name: 'Áo Manchester United mùa 2006-2007',
    price: 222000,
    oldPrice: 350000,
    images: [
      '../img/ao/ao_mu_2006-2007/ao_mu_2006-07.png',
      '../img/ao/ao_mu_2006-2007/logo_canh_tay_ao_mu_2006-07.jpg',
      '../img/ao/ao_mu_2006-2007/logo_clb_mu_2006-07.jpg',
      '../img/ao/ao_mu_2006-2007/lung_ao_mu_2006-07.jpg',
      '../img/ao/ao_mu_2006-2007/rooney.jpg',
      '../img/ao/ao_mu_2006-2007/size_ao_mu_2006-07.png',
    ],
    description: `Áo đá bóng của đội bóng Manchester United mùa 2006-2007 cực kỳ đẹp và đặc sắc.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Đỏ'],
    stock: 25,
    category: 'Áo đá bóng',
    brand: 'Local Brand XYZ',
  },
];
// Pants
const pants = [
  {
    id: 1,
    type: 'pants',
    name: 'Quần jeans dài Wash-Unisex',
    price: 550000,
    oldPrice: 690000,
    images: [
      '../img/quan/quan_jean_dai_wash_unisex/quan_jean_dai_wash_unisex.png',
      '../img/quan/quan_jean_dai_wash_unisex/quan_jean_dai_wash_unisex1.png',
      '../img/quan/quan_jean_dai_wash_unisex/quan_jean_dai_wash_unisex2.png',
      '../img/quan/quan_jean_dai_wash_unisex/quan_jean_dai_wash_unisex3.png',
      '../img/quan/quan_jean_dai_wash_unisex/quan_jean_dai_wash_unisex4.png',
    ],
    description: `Quần jeans wash nhẹ, unisex, chất liệu denim co giãn nhẹ, phù hợp đi chơi và dạo phố.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Xanh lam', 'Đen', 'Xam jean', 'Xanh đậm'],
    stock: 20,
    category: 'Quần jeans',
    brand: 'Local Brand XYZ',
  },
  {
    id: 2,
    type: 'pants',
    name: 'Quần jeans nam rách gối khóa zip',
    price: 600000,
    oldPrice: 750000,
    images: [
      '../img/quan/quan_jean_nam_rach_goi_khoa_zip/quan_jean_nam_rach_goi_khoa_zip.png',
      '../img/quan/quan_jean_nam_rach_goi_khoa_zip/quan_jean_nam_rach_goi_khoa_zip1.png',
      '../img/quan/quan_jean_nam_rach_goi_khoa_zip/quan_jean_nam_rach_goi_khoa_zip2.png',
      '../img/quan/quan_jean_nam_rach_goi_khoa_zip/quan_jean_nam_rach_goi_khoa_zip3.png',
      '../img/quan/quan_jean_nam_rach_goi_khoa_zip/quan_jean_nam_rach_goi_khoa_zip4.png',
      '../img/quan/quan_jean_nam_rach_goi_khoa_zip/quan_jean_nam_rach_goi_khoa_zip5.png',
    ],
    description: `Quần jeans nam form slim, rách gối cá tính, có khóa zip trang trí.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Xanh vitage'],
    stock: 18,
    category: 'Quần jeans',
    brand: 'Local Brand XYZ',
  },
  {
    id: 3,
    type: 'pants',
    name: 'Quần jeans túi hộp ống suông unisex',
    price: 620000,
    oldPrice: 780000,
    images: [
      '../img/quan/quan_jean_tui_hop_ong_suong_unisex/quan_jean_tui_hop_ong_suong_unisex.png',
      '../img/quan/quan_jean_tui_hop_ong_suong_unisex/quan_jean_tui_hop_ong_suong_unisex1.png',
      '../img/quan/quan_jean_tui_hop_ong_suong_unisex/quan_jean_tui_hop_ong_suong_unisex2.png',
    ],
    description: `Quần jeans túi hộp rộng rãi, phong cách đường phố, ống suông unisex.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Xanh jean', 'Xanh rêu'],
    stock: 22,
    category: 'Quần jeans',
    brand: 'Local Brand XYZ',
  },
  {
    id: 4,
    type: 'pants',
    name: 'Quần ống suông nỉ kẻ sọc',
    price: 450000,
    oldPrice: 580000,
    images: [
      '../img/quan/quan_ong_rong_in_soc_HongKong/quan_ong_rong_in_soc_HongKong.png',
      '../img/quan/quan_ong_rong_in_soc_HongKong/quan_ong_rong_in_soc_HongKong1.png',
      '../img/quan/quan_ong_rong_in_soc_HongKong/quan_ong_rong_in_soc_HongKong2.png',
      '../img/quan/quan_ong_rong_in_soc_HongKong/quan_ong_rong_in_soc_HongKong3.png',
      '../img/quan/quan_ong_rong_in_soc_HongKong/quan_ong_rong_in_soc_HongKong4.png',
    ],
    description: `Quần nỉ thể thao ống suông, kẻ sọc hai bên, thoải mái khi vận động.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Kẻ đen', 'Kẻ nâu', 'Kẻ xanh', 'Kẻ đỏ'],
    stock: 30,
    category: 'Quần thể thao',
    brand: 'Local Brand XYZ',
  },
  {
    id: 5,
    type: 'pants',
    name: 'Quần ống rộng vải kaki T-Home-Wide-Leg',
    price: 580000,
    oldPrice: 720000,
    images: [
      '../img/quan/quan_ong_rong_Thomes_Wide-leg_pants/quan_ong_rong_Thomes_Wide-leg_pants.png',
      '../img/quan/quan_ong_rong_Thomes_Wide-leg_pants/quan_ong_rong_Thomes_Wide-leg_pants1.png',
      '../img/quan/quan_ong_rong_Thomes_Wide-leg_pants/quan_ong_rong_Thomes_Wide-leg_pants2.png',
      '../img/quan/quan_ong_rong_Thomes_Wide-leg_pants/quan_ong_rong_Thomes_Wide-leg_pants3.png',
      '../img/quan/quan_ong_rong_Thomes_Wide-leg_pants/quan_ong_rong_Thomes_Wide-leg_pants4.png',
    ],
    description: `Quần kaki ống rộng form T-Home, vải dày dặn, thích hợp mùa thu đông.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Be', 'Đen'],
    stock: 25,
    category: 'Quần kaki',
    brand: 'Local Brand XYZ',
  },
  {
    id: 6,
    type: 'pants',
    name: 'Quần short jeans form rộng trên gối',
    price: 400000,
    oldPrice: 520000,
    images: [
      '../img/quan/quan_short_jean_form_rong_tren_goi/quan_short_jean_form_rong_tren_goi.png',
      '../img/quan/quan_short_jean_form_rong_tren_goi/quan_short_jean_form_rong_tren_goi1.png',
      '../img/quan/quan_short_jean_form_rong_tren_goi/quan_short_jean_form_rong_tren_goi2.png',
      '../img/quan/quan_short_jean_form_rong_tren_goi/quan_short_jean_form_rong_tren_goi3.png',
      '../img/quan/quan_short_jean_form_rong_tren_goi/quan_short_jean_form_rong_tren_goi4.png',
    ],
    description: `Quần short jeans form rộng, dài trên gối, dễ phối đồ mùa hè.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Xanh', 'Đen'],
    stock: 28,
    category: 'Quần short',
    brand: 'Local Brand XYZ',
  },
  {
    id: 7,
    type: 'pants',
    name: 'Quần short nỉ dây thun dài',
    price: 380000,
    oldPrice: 490000,
    images: [
      '../img/quan/quan_short_vai_ni_form_rong/quan_short_vai_ni_form_rong.png',
      '../img/quan/quan_short_vai_ni_form_rong/quan_short_vai_ni_form_rong1.png',
      '../img/quan/quan_short_vai_ni_form_rong/quan_short_vai_ni_form_rong2.png',
      '../img/quan/quan_short_vai_ni_form_rong/quan_short_vai_ni_form_rong3.png',
      '../img/quan/quan_short_vai_ni_form_rong/quan_short_vai_ni_form_rong4.png',
    ],
    description: `Quần short nỉ co giãn, có dây thun dài, thoải mái và năng động.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Đen', 'Xám'],
    stock: 32,
    category: 'Quần short',
    brand: 'Local Brand XYZ',
  },
  {
    id: 8,
    type: 'pants',
    name: 'Quần âu ống suông vải trơn',
    price: 650000,
    oldPrice: 800000,
    images: [
      '../img/quan/quan_au_nam_ong_suong/quan_au_1.png',
      '../img/quan/quan_au_nam_ong_suong/quan_au_2.png',
      '../img/quan/quan_au_nam_ong_suong/quan_au_black.png',
      '../img/quan/quan_au_nam_ong_suong/quan_au_gray.png',
      '../img/quan/quan_au_nam_ong_suong/quan_au_milky_white.png',
      '../img/quan/quan_au_nam_ong_suong/size.png',
    ],
    description: `Quần âu ống suông vải trơn, thích hợp mặc đi làm hoặc sự kiện.`,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Đen', 'Xám', 'Be'],
    stock: 15,
    category: 'Quần âu',
    brand: 'Local Brand XYZ',
  },
];

// Shoes
const shoes = [
  {
    id: 1,
    type: 'shoes',
    name: 'Giày Adidas SuperStar',
    price: 1800000,
    oldPrice: 2100000,
    images: [
      '../img/giay/giay_adidas_adiform_superstar/giay_adidas_adiform_superstar.png',
      '../img/giay/giay_adidas_adiform_superstar/giay_adidas_adiform_superstar1.png',
      '../img/giay/giay_adidas_adiform_superstar/giay_adidas_adiform_superstar2.png',
      '../img/giay/giay_adidas_adiform_superstar/giay_adidas_adiform_superstar3.png',
      '../img/giay/giay_adidas_adiform_superstar/giay_adidas_adiform_superstar4.png',
    ],
    description: `Giày Adidas SuperStar cổ điển với thiết kế mũi vỏ sò đặc trưng.`,
    sizes: ['38', '39', '40', '41', '42', '43'],
    colors: ['Trắng', 'Đen'],
    stock: 20,
    category: 'Giày sneaker',
    brand: 'Adidas',
  },
  {
    id: 2,
    type: 'shoes',
    name: 'Giày Chelsea Boot nam da bò',
    price: 2200000,
    oldPrice: 2500000,
    images: [
      '../img/giay/giay_chelsea_boot_nam_da_bo/giay_chelsea_boot_nam_da_bo.png',
      '../img/giay/giay_chelsea_boot_nam_da_bo/giay_chelsea_boot_nam_da_bo1.png',
      '../img/giay/giay_chelsea_boot_nam_da_bo/giay_chelsea_boot_nam_da_bo2.png',
      '../img/giay/giay_chelsea_boot_nam_da_bo/giay_chelsea_boot_nam_da_bo3.png',
      '../img/giay/giay_chelsea_boot_nam_da_bo/giay_chelsea_boot_nam_da_bo4.png',
    ],
    description: `Chelsea Boot nam da bò thật, phong cách sang trọng.`,
    sizes: ['39', '40', '41', '42', '43', '44'],
    colors: ['Đen'],
    stock: 12,
    category: 'Giày boot',
    brand: 'Local Brand XYZ',
  },
  {
    id: 3,
    type: 'shoes',
    name: 'Giày Converse Chuck-Taylor-Chrismas',
    price: 1500000,
    oldPrice: 1700000,
    images: [
      '../img/giay/giay_converse_Chuck_Taylor_Christmas/giay_converse_Chuck_Taylor_Christmas.png',
      '../img/giay/giay_converse_Chuck_Taylor_Christmas/giay_converse_Chuck_Taylor_Christmas1.png',
      '../img/giay/giay_converse_Chuck_Taylor_Christmas/giay_converse_Chuck_Taylor_Christmas2.png',
      '../img/giay/giay_converse_Chuck_Taylor_Christmas/giay_converse_Chuck_Taylor_Christmas3.png',
      '../img/giay/giay_converse_Chuck_Taylor_Christmas/giay_converse_Chuck_Taylor_Christmas4.png',
    ],
    description: `Converse Chuck Taylor phiên bản Giáng Sinh, họa tiết đặc biệt.`,
    sizes: ['38', '39', '40', '41', '42', '43'],
    colors: ['Xanh'],
    stock: 18,
    category: 'Giày sneaker',
    brand: 'Converse',
  },
  {
    id: 4,
    type: 'shoes',
    name: 'Giày Jordan Four Military',
    price: 3500000,
    oldPrice: 3800000,
    images: [
      '../img/giay/giay_jordan_4_Military/giay_jordan_4_Military.png',
      '../img/giay/giay_jordan_4_Military/giay_jordan_4_Military1.png',
      '../img/giay/giay_jordan_4_Military/giay_jordan_4_Military2.png',
      '../img/giay/giay_jordan_4_Military/giay_jordan_4_Military3.png',
      '../img/giay/giay_jordan_4_Military/giay_jordan_4_Military4.png',
    ],
    description: `Jordan Four Military phong cách thể thao, chất liệu cao cấp.`,
    sizes: ['39', '40', '41', '42', '43', '44'],
    colors: ['Trắng đen'],
    stock: 10,
    category: 'Giày sneaker',
    brand: 'Nike',
  },
  {
    id: 5,
    type: 'shoes',
    name: 'Giày New Balance',
    price: 1900000,
    oldPrice: 2200000,
    images: [
      '../img/giay/giay_new_balance_574/giay_new_balance_574.png',
      '../img/giay/giay_new_balance_574/giay_new_balance_5741.png',
      '../img/giay/giay_new_balance_574/giay_new_balance_5742.png',
      '../img/giay/giay_new_balance_574/giay_new_balance_5743.png',
      '../img/giay/giay_new_balance_574/giay_new_balance_5744.png',
    ],
    description: `Giày New Balance phong cách retro, êm ái khi di chuyển.`,
    sizes: ['38', '39', '40', '41', '42', '43'],
    colors: ['Đỏ đậm'],
    stock: 15,
    category: 'Giày sneaker',
    brand: 'Balance',
  },
  {
    id: 6,
    type: 'shoes',
    name: 'Giày Samba OG 3 sọc',
    price: 1700000,
    oldPrice: 1900000,
    images: [
      '../img/giay/giay_samba_OG_3_soc/giay_samba_OG_3_soc.png',
      '../img/giay/giay_samba_OG_3_soc/giay_samba_OG_3_soc1.png',
      '../img/giay/giay_samba_OG_3_soc/giay_samba_OG_3_soc2.png',
      '../img/giay/giay_samba_OG_3_soc/giay_samba_OG_3_soc3.png',
      '../img/giay/giay_samba_OG_3_soc/giay_samba_OG_3_soc4.png',
    ],
    description: `Giày Samba OG 3 sọc, kiểu dáng cổ điển, dễ phối đồ.`,
    sizes: ['38', '39', '40', '41', '42', '43'],
    colors: ['Đỏ'],
    stock: 22,
    category: 'Giày sneaker',
    brand: 'Adidas',
  },
  {
    id: 7,
    type: 'shoes',
    name: 'Giày Sneaker Blazer Mid 77',
    price: 2000000,
    oldPrice: 2300000,
    images: [
      '../img/giay/giay_sneaker_blazer_mid_77_co_cao/giay_sneaker_blazer_mid_77_co_cao.png',
      '../img/giay/giay_sneaker_blazer_mid_77_co_cao/giay_sneaker_blazer_mid_77_co_cao1.png',
      '../img/giay/giay_sneaker_blazer_mid_77_co_cao/giay_sneaker_blazer_mid_77_co_cao2.png',
      '../img/giay/giay_sneaker_blazer_mid_77_co_cao/giay_sneaker_blazer_mid_77_co_cao3.png',
      '../img/giay/giay_sneaker_blazer_mid_77_co_cao/giay_sneaker_blazer_mid_77_co_cao4.png',
    ],
    description: `Nike Blazer Mid 77 phong cách vintage, form cao.`,
    sizes: ['38', '39', '40', '41', '42', '43'],
    colors: ['Trắng đen'],
    stock: 14,
    category: 'Giày sneaker',
    brand: 'Nike',
  },
  {
    id: 8,
    type: 'shoes',
    name: 'Giày Air Jordan',
    price: 3200000,
    oldPrice: 3500000,
    images: [
      '../img/giay/giay_air_jordan_1_Retro_High_OG/giay_air_jordan_1.png',
      '../img/giay/giay_air_jordan_1_Retro_High_OG/giay_air_jordan_2.png',
      '../img/giay/giay_air_jordan_1_Retro_High_OG/giay_air_jordan_mau_nguoi.png',
      '../img/giay/giay_air_jordan_1_Retro_High_OG/giay_air_jordan_mocha.png',
      '../img/giay/giay_air_jordan_1_Retro_High_OG/giay_air_jordan_panda.png',
      '../img/giay/giay_air_jordan_1_Retro_High_OG/giay_air_jordan_red.png',
    ],
    description: `Air Jordan phong cách thể thao, đế êm và bền.`,
    sizes: ['39', '40', '41', '42', '43', '44'],
    colors: ['Đen', 'Trắng', 'Đỏ'],
    stock: 12,
    category: 'Giày sneaker',
    brand: 'Nike',
  },
];
